import '@hotwired/turbo-rails'
import 'controllers'
import 'custom/main'
import 'custom/add_to_cart'
import 'custom/order_modal'
import 'custom/manage_admin_order'
import 'custom/cancel_order'
import '@fontawesome/fontawesome-free'
